### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by arounds-team** [graycampbell/GCCountryPicker#16]
Hi
Please help me , countries are not sorting as currently,
How to fix it ?

![7i4nh8l4-pk](https://user-images.githubusercontent.com/38962448/40740547-31b2d03e-645a-11e8-9e54-8b206c9c5e64.jpg)

**Comment by graycampbell** [comment]
GCCountryPicker uses `UILocalizedIndexedCollation` to sort the countries alphabetically, and it works correctly with English, so I'm not sure why it wouldn't work with other languages as well.

I can try to take a closer look at why this might be happening. Is the language in your screenshot Russian?

**Comment by arounds-team** [comment]
@graycampbell you are right , the language is Russion.
Please let me know if there is any good news ))
Thanks

**Comment by graycampbell** [comment]
Now that I think about it, this was an oversight on my part. The country picker should be using the same localization as the app, not the device. If the device is using Russian, but the app is only localized for English, then the country picker should be using English, not Russian.

**Comment by graycampbell** [comment]
The localization issue I mentioned above has been fixed as of [Version 2.4.1](https://github.com/graycampbell/GCCountryPicker/releases/tag/2.4.1), so the sorting issue should no longer be a problem.
